rekab_sandbox:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dx-sandbox-492810
      dataset: dbt_dev
      location: US
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
      keyfile: /root/.dbt/service_account.json
    prod:
      type: bigquery
      method: oauth
      project: dx-sandbox-492810
      dataset: dbt_dev
      location: US
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
  target: dev
